spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/items;MODE=MYSQL;
    username: order-user
    password: order-pass

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      encoding: UTF-8

logging:
  level:
    root: warn
